[workspace]
# members = ["src/oracle_canister", "src/register_agent"]
members = ["src/oracle_canister", "src/solidity-helper"]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.4"
candid = "0.8"
# Using fixed chrono version. See: https://infinityswap.atlassian.net/browse/EPROD-45
chrono = "=0.4.19"
clap = { version = "4.2.4", features = ["derive"] }
derive_more = "0.99"
did = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "did" }
dirs = "4.0.0"
ethereum-types = "0.14"
# infinityswap.atlassian.net/browse/EPROD-153 - We are currently depending on a commit, will be removed when new version is released
ethers-core = { git = "https://github.com/infinity-swap/ethers-rs", default-features = false, package = "ethers-core", branch = "evmc_fork" }
eth-signer = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "eth-signer" }
evm_adapter = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "evm_adapter" }
hex = "0.4"
ic-agent = "0.23.0"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", tag = "v0.3.45" }
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", tag = "v0.3.45" }
ic-stable-structures = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-stable-structures", tag = "v0.3.45" }
is20-token = { git = "https://github.com/infinity-swap/IS20", package = "is20-token", tag = "v1.10.39" }
jsonrpc-core = "18.0"
mockall = "0.11.4"
once_cell = "1.17"
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
rlp = "0.5"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.24", features = ["macros", "rt"] }
url = { version = "2.3.1", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
